INSERT INTO `car_make_model` (`make`,`model`) VALUES
('Acura','Legend'),
('Acura','Integra'),
('Acura','NSX'),
('Acura','Vigor'),
('Acura','TL'),
('Acura','RL'),
('Acura','SLX'),
('Acura','CL'),
('Acura','MDX'),
('Acura','RSX'),
('Acura','TSX'),
('Acura','RDX'),
('Acura','ZDX'),
('Alfa Romeo','164'),
('Alfa Romeo','Spider'),
('Aptera','Typ-1'),
('Aptera','2e'),
('Aptera','Type-1h'),
('Aston Martin','DB9'),
('Aston Martin','Vanquish S'),
('Aston Martin','DB9 Volante'),
('Aston Martin','V8 Vantage'),
('Aston Martin','Vantage'),
('Aston Martin','DBS'),
('Aston Martin','Rapide'),
('Aston Martin','V8 Vantage S'),
('Aston Martin','V12 Vantage'),
('Aston Martin','Virage'),
('Audi','80'),
('Audi','90'),
('Audi','100'),
('Audi','200'),
('Audi','V8'),
('Audi','Coupe Quattro'),
('Audi','S4'),
('Audi','Quattro'),
('Audi','Cabriolet'),
('Audi','riolet'),
('Audi','S6'),
('Audi','A6'),
('Audi','A4'),
('Audi','A8'),
('Audi','TT'),
('Audi','S8'),
('Audi','Allroad'),
('Audi','RS6'),
('Audi','RS 6'),
('Audi','A3'),
('Audi','Q7'),
('Audi','RS4'),
('Audi','RS 4'),
('Audi','S5'),
('Audi','R8'),
('Audi','A5'),
('Audi','Q5'),
('Audi','A7'),
('Bentley','Arnage'),
('Bentley','Continental'),
('Bentley','Azure'),
('Bentley','Continental GT'),
('Bentley','Continental Flying Spur'),
('Bentley','Continental GTC'),
('Bentley','Brooklands'),
('Bentley','Continental Super'),
('Bentley','Azure T'),
('Bentley','Mulsanne'),
('BMW','3 Series'),
('BMW','5 Series'),
('BMW','7 Series'),
('BMW','8 Series'),
('BMW','M5'),
('BMW','M3'),
('BMW','Z3'),
('BMW','X5'),
('BMW','M'),
('BMW','Z8'),
('BMW','525'),
('BMW','530'),
('BMW','745'),
('BMW','760'),
('BMW','Z4'),
('BMW','6 Series'),
('BMW','325'),
('BMW','545'),
('BMW','645'),
('BMW','X3'),
('BMW','330'),
('BMW','550'),
('BMW','650'),
('BMW','750'),
('BMW','M6'),
('BMW','M Roadster'),
('BMW','Z4 M'),
('BMW','Alpina B7'),
('BMW','1 Series'),
('BMW','X6'),
('BMW','Z4 M Roadster'),
('BMW','X5 M'),
('BMW','X6 M'),
('Bugatti','Veyron'),
('Buick','LeSabre'),
('Buick','Regal'),
('Buick','Century'),
('Buick','Riviera'),
('Buick','Skylark'),
('Buick','Coachbuilder'),
('Buick','Estate'),
('Buick','Electra'),
('Buick','Reatta'),
('Buick','Park Avenue'),
('Buick','Roadmaster'),
('Buick','Hearse'),
('Buick','Rendezvous'),
('Buick','Rainier'),
('Buick','LaCrosse'),
('Buick','Terraza'),
('Buick','Lucerne'),
('Buick','Enclave'),
('Buick','Verano'),
('Cadillac','Seville'),
('Cadillac','Allante'),
('Cadillac','Brougham'),
('Cadillac','DeVille'),
('Cadillac','Eldorado'),
('Cadillac','Fleetwood'),
('Cadillac','Sixty Special'),
('Cadillac','Catera'),
('Cadillac','Escalade'),
('Cadillac','Escalade EXT'),
('Cadillac','CTS'),
('Cadillac','Escalade ESV'),
('Cadillac','SRX'),
('Cadillac','XLR'),
('Cadillac','STS'),
('Cadillac','DTS'),
('Cadillac','XLR-V'),
('Cadillac','CTS-V'),
('Cadillac','STS-V'),
('Chevrolet','Caprice'),
('Chevrolet','1500'),
('Chevrolet','2500'),
('Chevrolet','3500'),
('Chevrolet','APV'),
('Chevrolet','Astro'),
('Chevrolet','Beretta'),
('Chevrolet','Blazer'),
('Chevrolet','Camaro'),
('Chevrolet','Cavalier'),
('Chevrolet','Corsica'),
('Chevrolet','Corvette'),
('Chevrolet','G-Series G10'),
('Chevrolet','G-Series G20'),
('Chevrolet','G-Series G30'),
('Chevrolet','Lumina'),
('Chevrolet','Lumina APV'),
('Chevrolet','S10 Blazer'),
('Chevrolet','S10'),
('Chevrolet','Sportvan G10'),
('Chevrolet','Sportvan G20'),
('Chevrolet','Sportvan G30'),
('Chevrolet','Suburban 1500'),
('Chevrolet','Suburban 2500'),
('Chevrolet','Caprice Classic'),
('Chevrolet','Impala SS'),
('Chevrolet','Impala'),
('Chevrolet','K5 Blazer'),
('Chevrolet','Monte Carlo'),
('Chevrolet','Tahoe'),
('Chevrolet','Express 1500'),
('Chevrolet','Express 2500'),
('Chevrolet','Express 3500'),
('Chevrolet','G-Series 1500'),
('Chevrolet','G-Series 2500'),
('Chevrolet','Malibu'),
('Chevrolet','G-Series 3500'),
('Chevrolet','Venture'),
('Chevrolet','Metro'),
('Chevrolet','Prizm'),
('Chevrolet','Tracker'),
('Chevrolet','Silverado'),
('Chevrolet','Silverado 1500'),
('Chevrolet','Silverado 2500'),
('Chevrolet','Silverado 3500'),
('Chevrolet','Avalanche'),
('Chevrolet','Trailblazer'),
('Chevrolet','Avalanche 1500'),
('Chevrolet','Avalanche 2500'),
('Chevrolet','SSR'),
('Chevrolet','TrailBlazer'),
('Chevrolet','Aveo'),
('Chevrolet','Classic'),
('Chevrolet','Colorado'),
('Chevrolet','Cobalt'),
('Chevrolet','Equinox'),
('Chevrolet','Uplander'),
('Chevrolet','Suburban'),
('Chevrolet','Silverado 3500HD'),
('Chevrolet','HHR Panel'),
('Chevrolet','Malibu Maxx'),
('Chevrolet','HHR'),
('Chevrolet','Silverado Hybrid'),
('Chevrolet','Express'),
('Chevrolet','Cobalt SS'),
('Chevrolet','Traverse'),
('Chevrolet','Volt'),
('Chevrolet','Cruze'),
('Chevrolet','Sonic'),
('Chrysler','Fifth Ave'),
('Chrysler','Imperial'),
('Chrysler','LeBaron'),
('Chrysler','New Yorker'),
('Chrysler','Town & Country'),
('Chrysler','Concorde'),
('Chrysler','LHS'),
('Chrysler','Cirrus'),
('Chrysler','Sebring'),
('Chrysler','300M'),
('Chrysler','300'),
('Chrysler','Grand Voyager'),
('Chrysler','Voyager'),
('Chrysler','PT Cruiser'),
('Chrysler','Prowler'),
('Chrysler','Crossfire'),
('Chrysler','Pacifica'),
('Chrysler','300C'),
('Chrysler','Crossfire Roadster'),
('Chrysler','Aspen'),
('Chrysler','200'),
('Corbin','Sparrow'),
('Daewoo','Lanos'),
('Daewoo','Leganza'),
('Daewoo','Nubira'),
('Daihatsu','Charade'),
('Daihatsu','Rocky'),
('Dodge','Viper'),
('Dodge','Caravan'),
('Dodge','Colt'),
('Dodge','D150 Club'),
('Dodge','D150'),
('Dodge','D250 Club'),
('Dodge','D250'),
('Dodge','D350 Club'),
('Dodge','D350'),
('Dodge','Dakota Club'),
('Dodge','Dakota'),
('Dodge','Daytona'),
('Dodge','Dynasty'),
('Dodge','Grand Caravan'),
('Dodge','Monaco'),
('Dodge','Ram 50'),
('Dodge','Ram Van B150'),
('Dodge','Ram Van B250'),
('Dodge','Ram Van B350'),
('Dodge','Ram Wagon B150'),
('Dodge','Ram Wagon B250'),
('Dodge','Ram Wagon B350'),
('Dodge','Ramcharger'),
('Dodge','Shadow'),
('Dodge','Spirit'),
('Dodge','Stealth'),
('Dodge','Viper RT/10'),
('Dodge','Intrepid'),
('Dodge','Ram'),
('Dodge','Ram 1500'),
('Dodge','Ram 2500'),
('Dodge','Ram 3500'),
('Dodge','Avenger'),
('Dodge','Neon'),
('Dodge','Ram 1500 Club'),
('Dodge','Ram 2500 Club'),
('Dodge','Ram 3500 Club'),
('Dodge','Ram Van 1500'),
('Dodge','Ram Van 2500'),
('Dodge','Ram Van 3500'),
('Dodge','Stratus'),
('Dodge','Durango'),
('Dodge','Charger'),
('Dodge','Magnum'),
('Dodge','Sprinter'),
('Dodge','Nitro'),
('Dodge','Caliber'),
('Dodge','Challenger'),
('Dodge','Journey'),
('Eagle','Talon'),
('Eagle','Premier'),
('Eagle','Summit'),
('Eagle','Vision'),
('Ferrari','F430'),
('Ferrari','612 Scaglietti'),
('Ferrari','F430 Spider'),
('Ferrari','599 GTB Fiorano'),
('Ferrari','430 Scuderia'),
('Ferrari','California'),
('Ferrari','458 Italia'),
('Ferrari','FF'),
('FIAT','500'),
('Fiat','Nuova 500'),
('Foose','Hemisfear'),
('Ford','Taurus'),
('Ford','F-Series'),
('Ford','Mustang'),
('Ford','Thunderbird'),
('Ford','Tempo'),
('Ford','Aerostar'),
('Ford','Escort'),
('Ford','Ranger'),
('Ford','E-Series'),
('Ford','Probe'),
('Ford','LTD Crown Victoria'),
('Ford','Bronco II'),
('Ford','Bronco'),
('Ford','Festiva'),
('Ford','Explorer'),
('Ford','Crown Victoria'),
('Ford','Club Wagon'),
('Ford','Econoline E150'),
('Ford','Econoline E250'),
('Ford','Econoline E350'),
('Ford','F150'),
('Ford','F250'),
('Ford','F350'),
('Ford','Lightning'),
('Ford','Aspire'),
('Ford','Windstar'),
('Ford','Contour'),
('Ford','Expedition'),
('Ford','Th!nk'),
('Ford','Explorer Sport Trac'),
('Ford','Escape'),
('Ford','Excursion'),
('Ford','Explorer Sport'),
('Ford','Focus'),
('Ford','TH!NK'),
('Ford','Fiesta'),
('Ford','ZX2'),
('Ford','Escort ZX2'),
('Ford','Freestar'),
('Ford','E150'),
('Ford','E250'),
('Ford','E350'),
('Ford','GT'),
('Ford','Freestyle'),
('Ford','Five Hundred'),
('Ford','F-250 Super Duty'),
('Ford','F-350 Super Duty'),
('Ford','E-350 Super Duty'),
('Ford','E-350 Super Duty Van'),
('Ford','Fusion'),
('Ford','F-Series Super Duty'),
('Ford','GT500'),
('Ford','Edge'),
('Ford','Expedition EL'),
('Ford','Taurus X'),
('Ford','F450'),
('Ford','Flex'),
('Ford','Transit Connect'),
('Ford','C-MAX Hybrid'),
('Ford','Focus ST'),
('Geo','Metro'),
('Geo','Prizm'),
('Geo','Storm'),
('Geo','Tracker'),
('GMC','1500'),
('GMC','2500'),
('GMC','3500'),
('GMC','1500 Club Coupe'),
('GMC','2500 Club Coupe'),
('GMC','3500 Club Coupe'),
('GMC','Jimmy'),
('GMC','Rally Wagon 1500'),
('GMC','Rally Wagon 2500'),
('GMC','Rally Wagon 3500'),
('GMC','Safari'),
('GMC','Sonoma Club'),
('GMC','Sonoma'),
('GMC','Suburban 1500'),
('GMC','Suburban 2500'),
('GMC','Vandura 1500'),
('GMC','Vandura 2500'),
('GMC','Vandura 3500'),
('GMC','Yukon'),
('GMC','Sonoma Club Coupe'),
('GMC','Rally Wagon G2500'),
('GMC','Rally Wagon G3500'),
('GMC','Vandura G1500'),
('GMC','Vandura G2500'),
('GMC','Vandura G3500'),
('GMC','Savana 1500'),
('GMC','Savana 2500'),
('GMC','Savana 3500'),
('GMC','Envoy'),
('GMC','EV1'),
('GMC','Sierra 1500'),
('GMC','Sierra 2500'),
('GMC','Sierra 3500'),
('GMC','Yukon Denali'),
('GMC','Yukon XL 1500'),
('GMC','Yukon XL 2500'),
('GMC','Envoy XL'),
('GMC','Canyon'),
('GMC','Envoy XUV'),
('GMC','Sierra Denali'),
('GMC','Sierra 3500HD'),
('GMC','Sierra 2500HD'),
('GMC','Yukon XL'),
('GMC','Savana Cargo Van'),
('GMC','Sierra Hybrid'),
('GMC','Savana'),
('GMC','Acadia'),
('GMC','Sierra'),
('GMC','Terrain'),
('Holden','VS Commodore'),
('Holden','Monaro'),
('Honda','Civic'),
('Honda','Accord'),
('Honda','Prelude'),
('Honda','del Sol'),
('Honda','Passport'),
('Honda','Odyssey'),
('Honda','CR-V'),
('Honda','Del Sol'),
('Honda','Insight'),
('Honda','S2000'),
('Honda','Pilot'),
('Honda','Element'),
('Honda','Civic Si'),
('Honda','Civic GX'),
('Honda','Ridgeline'),
('Honda','Fit'),
('Honda','Accord Crosstour'),
('Honda','CR-Z'),
('Honda','FCX Clarity'),
('Honda','Crosstour'),
('HUMMER','H1'),
('HUMMER','H2'),
('Hummer','H2 SUT'),
('Hummer','H2 SUV'),
('Hummer','H3'),
('Hummer','H2'),
('HUMMER','H3T'),
('HUMMER','H3'),
('Hyundai','Elantra'),
('Hyundai','Excel'),
('Hyundai','Scoupe'),
('Hyundai','Sonata'),
('Hyundai','Accent'),
('Hyundai','Tiburon'),
('Hyundai','Santa Fe'),
('Hyundai','XG300'),
('Hyundai','XG350'),
('Hyundai','Tucson'),
('Hyundai','Azera'),
('Hyundai','Veracruz'),
('Hyundai','Entourage'),
('Hyundai','Genesis'),
('Hyundai','Genesis Coupe'),
('Hyundai','Equus'),
('Hyundai','HED-5'),
('Hyundai','Veloster'),
('Infiniti','G'),
('Infiniti','M'),
('Infiniti','Q'),
('Infiniti','J'),
('Infiniti','I'),
('Infiniti','QX'),
('Infiniti','G35'),
('Infiniti','FX'),
('Infiniti','QX56'),
('Infiniti','G37'),
('Infiniti','EX'),
('Infiniti','G25'),
('Infiniti','IPL G'),
('Infiniti','JX'),
('Isuzu','Amigo'),
('Isuzu','Impulse'),
('Isuzu','Rodeo'),
('Isuzu','Space'),
('Isuzu','Stylus'),
('Isuzu','Trooper'),
('Isuzu','Hombre'),
('Isuzu','Oasis'),
('Isuzu','Hombre Space'),
('Isuzu','VehiCROSS'),
('Isuzu','Rodeo Sport'),
('Isuzu','Axiom'),
('Isuzu','Ascender'),
('Isuzu','i-Series'),
('Isuzu','i-280'),
('Isuzu','i-350'),
('Isuzu','i-290'),
('Isuzu','i-370'),
('Jaguar','XJ Series'),
('Jaguar','XK Series'),
('Jaguar','S-Type'),
('Jaguar','X-Type'),
('Jaguar','XK'),
('Jaguar','XJ'),
('Jaguar','XF'),
('Jeep','Cherokee'),
('Jeep','Comanche'),
('Jeep','Wrangler'),
('Jeep','Grand Cherokee'),
('Jeep','Liberty'),
('Jeep','Commander'),
('Jeep','Compass'),
('Jeep','Patriot'),
('Kia','Sephia'),
('Kia','Sportage'),
('Kia','Mentor'),
('Kia','Spectra'),
('Kia','Rio'),
('Kia','Optima'),
('Kia','Sedona'),
('Kia','Sorento'),
('Kia','Amanti'),
('Kia','Spectra5'),
('Kia','Carens'),
('Kia','Rondo'),
('Kia','Rio5'),
('Kia','Mohave/Borrego'),
('Kia','Borrego'),
('Kia','Soul'),
('Kia','Forte'),
('Lamborghini','Diablo'),
('Lamborghini','Countach'),
('Lamborghini','Murciélago'),
('Lamborghini','Gallardo'),
('Lamborghini','Reventón'),
('Lamborghini','Murciélago LP640'),
('Lamborghini','Aventador'),
('Land Rover','Range Rover'),
('Land Rover','Sterling'),
('Land Rover','Defender'),
('Land Rover','Range Rover Classic'),
('Land Rover','Defender 110'),
('Land Rover','Discovery'),
('Land Rover','Defender 90'),
('Land Rover','Discovery Series II'),
('Land Rover','Freelander'),
('Land Rover','LR3'),
('Land Rover','Range Rover Sport'),
('Land Rover','LR2'),
('Land Rover','LR4'),
('Land Rover','Defender Ice Edition'),
('Land Rover','Range Rover Evoque'),
('Lexus','LS'),
('Lexus','ES'),
('Lexus','SC'),
('Lexus','GS'),
('Lexus','LX'),
('Lexus','RX'),
('Lexus','IS'),
('Lexus','GX'),
('Lexus','RX Hybrid'),
('Lexus','IS-F'),
('Lexus','IS F'),
('Lexus','LS Hybrid'),
('Lexus','HS'),
('Lexus','CT'),
('Lexus','LFA'),
('Lincoln','Continental'),
('Lincoln','Continental Mark VII'),
('Lincoln','Town Car'),
('Lincoln','Mark VII'),
('Lincoln','Mark VIII'),
('Lincoln','Navigator'),
('Lincoln','LS'),
('Lincoln','Blackwood'),
('Lincoln','Aviator'),
('Lincoln','Zephyr'),
('Lincoln','Mark LT'),
('Lincoln','MKX'),
('Lincoln','MKZ'),
('Lincoln','Navigator L'),
('Lincoln','MKS'),
('Lincoln','MKT'),
('Lotus','Elan'),
('Lotus','Esprit'),
('Lotus','Exige'),
('Lotus','Elise'),
('Lotus','Evora'),
('Maserati','228'),
('Maserati','430'),
('Maserati','Karif'),
('Maserati','Spyder'),
('Maserati','Gran Sport'),
('Maserati','Quattroporte'),
('Maserati','Coupe'),
('Maserati','GranSport'),
('Maserati','GranTurismo'),
('Maybach','57'),
('Maybach','62'),
('Maybach','57S'),
('Maybach','Landaulet'),
('Mazda','626'),
('Mazda','929'),
('Mazda','B-Series'),
('Mazda','MX-6'),
('Mazda','Familia'),
('Mazda','MX-5'),
('Mazda','MPV'),
('Mazda','RX-7'),
('Mazda','Navajo'),
('Mazda','323'),
('Mazda','Protege'),
('Mazda','MX-3'),
('Mazda','B-Series Plus'),
('Mazda','Miata MX-5'),
('Mazda','Millenia'),
('Mazda','B2500'),
('Mazda','Tribute'),
('Mazda','Protege5'),
('Mazda','Mazda6'),
('Mazda','Mazda3'),
('Mazda','RX-8'),
('Mazda','Mazda6 5-Door'),
('Mazda','Mazda5'),
('Mazda','Mazda6 Sport'),
('Mazda','Mazdaspeed6'),
('Mazda','CX-7'),
('Mazda','Mazdaspeed 3'),
('Mazda','CX-9'),
('Mazda','Mazda2'),
('Mazda','CX-5'),
('Mazda','MAZDA6'),
('McLaren','MP4-12C'),
('Mercedes-Benz','S-Class'),
('Mercedes-Benz','E-Class'),
('Mercedes-Benz','SL-Class'),
('Mercedes-Benz','W201'),
('Mercedes-Benz','190E'),
('Mercedes-Benz','300CE'),
('Mercedes-Benz','300D'),
('Mercedes-Benz','300E'),
('Mercedes-Benz','300SD'),
('Mercedes-Benz','300SE'),
('Mercedes-Benz','300SL'),
('Mercedes-Benz','300TE'),
('Mercedes-Benz','400E'),
('Mercedes-Benz','400SE'),
('Mercedes-Benz','500E'),
('Mercedes-Benz','500SEL'),
('Mercedes-Benz','500SL'),
('Mercedes-Benz','600SEL'),
('Mercedes-Benz','C-Class'),
('Mercedes-Benz','400SEL'),
('Mercedes-Benz','500SEC'),
('Mercedes-Benz','600SEC'),
('Mercedes-Benz','600SL'),
('Mercedes-Benz','SLK-Class'),
('Mercedes-Benz','M-Class'),
('Mercedes-Benz','CL-Class'),
('Mercedes-Benz','CLK-Class'),
('Mercedes-Benz','G-Class'),
('Mercedes-Benz','SLR McLaren'),
('Mercedes-Benz','CLS-Class'),
('Mercedes-Benz','G55 AMG'),
('Mercedes-Benz','SL65 AMG'),
('Mercedes-Benz','R-Class'),
('Mercedes-Benz','GL-Class'),
('Mercedes-Benz','SLK55 AMG'),
('Mercedes-Benz','CL65 AMG'),
('Mercedes-Benz','Sprinter'),
('Mercedes-Benz','GLK-Class'),
('Mercedes-Benz','SLS AMG'),
('Mercedes-Benz','SLS-Class'),
('Mercedes-Benz','Sprinter 2500'),
('Mercedes-Benz','Sprinter 3500'),
('Mercury','Sable'),
('Mercury','Topaz'),
('Mercury','Grand Marquis'),
('Mercury','Cougar'),
('Mercury','Tracer'),
('Mercury','Capri'),
('Mercury','Villager'),
('Mercury','Mystique'),
('Mercury','Mountaineer'),
('Mercury','Marauder'),
('Mercury','Monterey'),
('Mercury','Montego'),
('Mercury','Mariner'),
('Mercury','Milan'),
('MINI','MINI'),
('MINI','Cooper'),
('MINI','Clubman'),
('MINI','Cooper Clubman'),
('MINI','Countryman'),
('MINI','Cooper Countryman'),
('Mitsubishi','Truck'),
('Mitsubishi','Mirage'),
('Mitsubishi','L300'),
('Mitsubishi','Galant'),
('Mitsubishi','Precis'),
('Mitsubishi','Pajero'),
('Mitsubishi','Eclipse'),
('Mitsubishi','GTO'),
('Mitsubishi','Sigma'),
('Mitsubishi','Chariot'),
('Mitsubishi','Diamante'),
('Mitsubishi','RVR'),
('Mitsubishi','3000GT'),
('Mitsubishi','Expo'),
('Mitsubishi','Mighty Max Macro'),
('Mitsubishi','Mighty Max'),
('Mitsubishi','Montero'),
('Mitsubishi','Expo LRV'),
('Mitsubishi','Challenger'),
('Mitsubishi','Montero Sport'),
('Mitsubishi','Lancer'),
('Mitsubishi','Lancer Evolution'),
('Mitsubishi','Outlander'),
('Mitsubishi','Endeavor'),
('Mitsubishi','Raider'),
('Mitsubishi','Tundra'),
('Mitsubishi','Outlander Sport'),
('Mitsubishi','i-MiEV'),
('Morgan','Aero 8'),
('Nissan','Maxima'),
('Nissan','Datsun/Nissan Z-car'),
('Nissan','300ZX'),
('Nissan','Sentra'),
('Nissan','240SX'),
('Nissan','NX'),
('Nissan','Pathfinder'),
('Nissan','Stanza'),
('Nissan','Altima'),
('Nissan','Quest'),
('Nissan','200SX'),
('Nissan','Frontier'),
('Nissan','Xterra'),
('Nissan','350Z'),
('Nissan','Murano'),
('Nissan','Titan'),
('Nissan','Pathfinder Armada'),
('Nissan','Armada'),
('Nissan','350Z Roadster'),
('Nissan','Versa'),
('Nissan','Rogue'),
('Nissan','Cube'),
('Nissan','GT-R'),
('Nissan','370Z'),
('Nissan','Leaf'),
('Nissan','JUKE'),
('Nissan','cube'),
('Nissan','NV1500'),
('Nissan','NV2500'),
('Nissan','NV3500'),
('Oldsmobile','88'),
('Oldsmobile','98'),
('Oldsmobile','Achieva'),
('Oldsmobile','Bravada'),
('Oldsmobile','Ciera'),
('Oldsmobile','Custom Cruiser'),
('Oldsmobile','Cutlass Supreme'),
('Oldsmobile','Silhouette'),
('Oldsmobile','Toronado'),
('Oldsmobile','Cutlass Cruiser'),
('Oldsmobile','Aurora'),
('Oldsmobile','Cutlass'),
('Oldsmobile','LSS'),
('Oldsmobile','Regency'),
('Oldsmobile','Intrigue'),
('Oldsmobile','Alero'),
('Panoz','Esperante'),
('Peugeot','207'),
('Plymouth','Laser'),
('Plymouth','Acclaim'),
('Plymouth','Colt'),
('Plymouth','Colt Vista'),
('Plymouth','Grand Voyager'),
('Plymouth','Sundance'),
('Plymouth','Voyager'),
('Plymouth','Neon'),
('Plymouth','Breeze'),
('Plymouth','Prowler'),
('Pontiac','6000'),
('Pontiac','Trans Sport'),
('Pontiac','Sunbird'),
('Pontiac','LeMans'),
('Pontiac','Firefly'),
('Pontiac','Grand Am'),
('Pontiac','Firebird'),
('Pontiac','Turbo Firefly'),
('Pontiac','Grand Prix'),
('Pontiac','Grand Prix Turbo'),
('Pontiac','Bonneville'),
('Pontiac','Firebird Formula'),
('Pontiac','Sunfire'),
('Pontiac','Montana'),
('Pontiac','Aztek'),
('Pontiac','Vibe'),
('Pontiac','GTO'),
('Pontiac','G6'),
('Pontiac','Daewoo Kalos'),
('Pontiac','Monterey'),
('Pontiac','Montana SV6'),
('Pontiac','Torrent'),
('Pontiac','Solstice'),
('Pontiac','G5'),
('Pontiac','G8'),
('Pontiac','G3'),
('Porsche','911'),
('Porsche','928'),
('Porsche','944'),
('Porsche','968'),
('Porsche','Boxster'),
('Porsche','Cayenne'),
('Porsche','Carrera GT'),
('Porsche','Cayman'),
('Porsche','Panamera'),
('Ram','1500'),
('Ram','2500'),
('Ram','3500'),
('Ram','Dakota'),
('Ram','C/V'),
('Rolls-Royce','Phantom'),
('Rolls-Royce','Ghost'),
('Saab','900'),
('Saab','9000'),
('Saab','9-3'),
('Saab','9-5'),
('Saab','9-7X'),
('Saab','9-2X'),
('Saab','9-4X'),
('Saturn','S-Series'),
('Saturn','L-Series'),
('Saturn','VUE'),
('Saturn','Ion'),
('Saturn','Relay'),
('Saturn','Vue'),
('Saturn','Outlook'),
('Saturn','Aura'),
('Saturn','Sky'),
('Saturn','Astra'),
('Scion','xA'),
('Scion','xB'),
('Scion','tC'),
('Scion','xD'),
('Scion','iQ'),
('Scion','FR-S'),
('Smart','Fortwo'),
('Spyker','C8 Spyder'),
('Spyker','C8 Spyder Wide Body'),
('Spyker','C8 Laviolette'),
('Spyker','C8 Double 12 S'),
('Spyker Cars','C8'),
('Subaru','Legacy'),
('Subaru','Justy'),
('Subaru','Loyale'),
('Subaru','XT'),
('Subaru','Alcyone SVX'),
('Subaru','SVX'),
('Subaru','Impreza'),
('Subaru','Forester'),
('Subaru','Outback'),
('Subaru','Outback Sport'),
('Subaru','Baja'),
('Subaru','Tribeca'),
('Subaru','B9 Tribeca'),
('Subaru','Impreza WRX'),
('Subaru','BRZ'),
('Suzuki','Sidekick'),
('Suzuki','Swift'),
('Suzuki','SJ'),
('Suzuki','Samurai'),
('Suzuki','Esteem'),
('Suzuki','X-90'),
('Suzuki','Vitara'),
('Suzuki','Grand Vitara'),
('Suzuki','XL-7'),
('Suzuki','Aerio'),
('Suzuki','Daewoo Lacetti'),
('Suzuki','Daewoo Magnus'),
('Suzuki','Forenza'),
('Suzuki','Verona'),
('Suzuki','Reno'),
('Suzuki','XL7'),
('Suzuki','SX4'),
('Suzuki','Equator'),
('Suzuki','Kizashi'),
('Tesla','Roadster'),
('Tesla','Model S'),
('Toyota','Previa'),
('Toyota','Camry'),
('Toyota','4Runner'),
('Toyota','Celica'),
('Toyota','Corolla'),
('Toyota','Cressida'),
('Toyota','Land Cruiser'),
('Toyota','MR2'),
('Toyota','Paseo'),
('Toyota','Supra'),
('Toyota','Tercel'),
('Toyota','Xtra'),
('Toyota','T100'),
('Toyota','Avalon'),
('Toyota','T100 Xtra'),
('Toyota','Tacoma'),
('Toyota','Tacoma Xtra'),
('Toyota','RAV4'),
('Toyota','Sienna'),
('Toyota','Solara'),
('Toyota','Tundra'),
('Toyota','Ipsum'),
('Toyota','Echo'),
('Toyota','Highlander'),
('Toyota','Prius'),
('Toyota','Sequoia'),
('Toyota','Matrix'),
('Toyota','Yaris'),
('Toyota','Camry Solara'),
('Toyota','Highlander Hybrid'),
('Toyota','Camry Hybrid'),
('Toyota','FJ Cruiser'),
('Toyota','TundraMax'),
('Toyota','Venza'),
('Toyota','Prius v'),
('Toyota','Prius Plug-in Hybrid'),
('Toyota','Prius c'),
('Toyota','Prius Plug-in'),
('Volkswagen','Passat'),
('Volkswagen','Fox'),
('Volkswagen','Type 2'),
('Volkswagen','Cabriolet'),
('Volkswagen','GTI'),
('Volkswagen','Jetta'),
('Volkswagen','Corrado'),
('Volkswagen','Golf'),
('Volkswagen','Eurovan'),
('Volkswagen','riolet'),
('Volkswagen','Golf III'),
('Volkswagen','Jetta III'),
('Volkswagen','rio'),
('Volkswagen','New Beetle'),
('Volkswagen','Touareg'),
('Volkswagen','R32'),
('Volkswagen','Phaeton'),
('Volkswagen','Rabbit'),
('Volkswagen','Eos'),
('Volkswagen','GLI'),
('Volkswagen','Touareg 2'),
('Volkswagen','CC'),
('Volkswagen','Tiguan'),
('Volkswagen','Routan'),
('Volvo','240'),
('Volvo','740'),
('Volvo','940'),
('Volvo','960'),
('Volvo','850'),
('Volvo','S90'),
('Volvo','V90'),
('Volvo','C70'),
('Volvo','S70'),
('Volvo','V70'),
('Volvo','S80'),
('Volvo','S40'),
('Volvo','V40'),
('Volvo','S60'),
('Volvo','XC90'),
('Volvo','XC70'),
('Volvo','V50'),
('Volvo','C30'),
('Volvo','XC60'),
('Volvo','XC90');